### ISSUE TITLE
Implementation of repository pattern

### ISSUE THREAD

**Issue by Whallas** [awes-io/repository#3]
Hello, I think you are not achieving the benefits you preached about with your interface. The Eloquent jargon in your interface and the type hint to return an Eloquent model are coupling it to Eloquent: this hurts the repository pattern in this case. If a project were to eventually replace Eloquent, it will be difficult to do that.

**Comment by yevhenlisovenko** [comment]
Hey @Whallas 

Thanks for your message and suggestion!

You are right. For our case, it was too complex for the beginning. 

We discussed the team and decided to implement this in a new version.

Best,
Yevhen
